skip_frontmatter: false
exclude:
  - 'vendor/**/*'
  - 'spec/**/*'
  - 'app/views/kaminari/*'
linters:
  AltText:
    enabled: true

  InlineStyles:
    enabled: false

  LineLength:
    enabled: false
